/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UbicacionGanado;

import java.awt.Color;


public class GuiLeastCostPath extends javax.swing.JFrame{
    GuiMatriz gm = new GuiMatriz();
    /**
     * Creates new form f
     */
    public GuiLeastCostPath() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTítulo = new javax.swing.JLabel();
        jBareasProtegidas = new javax.swing.JButton();
        jBareasSinProtegidas = new javax.swing.JButton();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTítulo.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLTítulo.setForeground(new java.awt.Color(255, 255, 51));
        jLTítulo.setText("Ubicacion de la Ganaderia");
        getContentPane().add(jLTítulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 590, 60));

        jBareasProtegidas.setBackground(new java.awt.Color(51, 153, 255));
        jBareasProtegidas.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jBareasProtegidas.setText("Areas Protegidas");
        jBareasProtegidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBareasProtegidasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBareasProtegidasMouseExited(evt);
            }
        });
        jBareasProtegidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBareasProtegidasActionPerformed(evt);
            }
        });
        getContentPane().add(jBareasProtegidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 280, 50));

        jBareasSinProtegidas.setBackground(new java.awt.Color(51, 204, 0));
        jBareasSinProtegidas.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jBareasSinProtegidas.setText("Areas sin Proteccion");
        jBareasSinProtegidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBareasSinProtegidasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBareasSinProtegidasMouseExited(evt);
            }
        });
        jBareasSinProtegidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBareasSinProtegidasActionPerformed(evt);
            }
        });
        getContentPane().add(jBareasSinProtegidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 280, 50));

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPaqImagenes/fwer2.jpg"))); // NOI18N
        getContentPane().add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 545));

        pack();
    }// </editor-fold>//GEN-END:initComponents


  
    
    private void jBareasSinProtegidasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBareasSinProtegidasMouseEntered
        jBareasSinProtegidas.setBackground(Color.red);
    }//GEN-LAST:event_jBareasSinProtegidasMouseEntered

    private void jBareasSinProtegidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBareasSinProtegidasActionPerformed
        jBareasSinProtegidas.setFocusable(false);
        gm.opcion = 1;
        gm.show();
        dispose();
        
    }//GEN-LAST:event_jBareasSinProtegidasActionPerformed

    
    private void jBareasSinProtegidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBareasSinProtegidasMouseExited
        jBareasSinProtegidas.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_jBareasSinProtegidasMouseExited

    private void jBareasProtegidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBareasProtegidasActionPerformed
        gm.opcion = 2;
        gm.show();
        dispose();

    }//GEN-LAST:event_jBareasProtegidasActionPerformed

    private void jBareasProtegidasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBareasProtegidasMouseEntered
        jBareasProtegidas.setBackground(Color.red);
    }//GEN-LAST:event_jBareasProtegidasMouseEntered

    private void jBareasProtegidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBareasProtegidasMouseExited
        jBareasProtegidas.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_jBareasProtegidasMouseExited

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiLeastCostPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiLeastCostPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiLeastCostPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiLeastCostPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiLeastCostPath().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBareasProtegidas;
    public javax.swing.JButton jBareasSinProtegidas;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLTítulo;
    // End of variables declaration//GEN-END:variables


}