/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UbicacionGanado;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;



 
public class GuiMatriz extends javax.swing.JFrame{

    public int opcion;
    /**
     * Creates new form GuiMatriz
     */
    public GuiMatriz(){
        initComponents();
        setLocation(500, 300);
        cargarImagenes();
        setLocationRelativeTo(this);
        
        jLcosto.setText("La ruta más barata tiene el costo de: " );
    }
    
    public void dibujarMatriz(int matriz[][], int camino[]) throws IOException {
        jPanelMatriz.removeAll();
        jPanelMatriz.revalidate();
        jPanelMatriz.repaint();

        for (int i = 0; i < matriz.length; i++){
            for (int j = 0; j < matriz[i].length; j++) {
                int num = matriz[i][j];
                String ruta = "jPaqAssets\\" +  String.valueOf(num) + ".png";
                if (i < camino.length && camino[i] == j) {
                    ruta = "jPaqAssets\\" +  String.valueOf(num) + "r.png";
                }
                
                BufferedImage image = ImageIO.read(new File(ruta));
                ImageIcon imageIcon = new ImageIcon(image);
                int x = (50 * j);
                int y = (50 * i);
                JLabel img = new JLabel(imageIcon);
                jPanelMatriz.add(img, new AbsoluteConstraints(x, y, 50, 50));
            }
        }
    }
    
    public void cargarImagenes() {
        try {
            //ManejadorMatriz.cargarMatriz();
            dibujarMatriz(Areas.matriz, new int[0]);
        }
        catch(IOException e) {
            System.out.print(e.getMessage());
        }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBarecorridog = new javax.swing.JButton();
        jBregresar = new javax.swing.JButton();
        jLcosto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelMatriz = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBarecorridog.setBackground(new java.awt.Color(0, 102, 255));
        jBarecorridog.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBarecorridog.setText("Ver recorrido");
        jBarecorridog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBarecorridogActionPerformed(evt);
            }
        });
        getContentPane().add(jBarecorridog, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, -1, -1));

        jBregresar.setBackground(new java.awt.Color(0, 51, 204));
        jBregresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBregresar.setText("Regresar al Menú");
        jBregresar.setPreferredSize(new java.awt.Dimension(126, 28));
        jBregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregresarActionPerformed(evt);
            }
        });
        getContentPane().add(jBregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 150, 30));
        jBregresar.getAccessibleContext().setAccessibleParent(this);

        jLcosto.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLcosto.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(jLcosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 580, 100));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Areas ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 170, -1));

        jPanelMatriz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 51, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setLabel("regresar");
        jButton2.setPreferredSize(new java.awt.Dimension(126, 28));
        jPanelMatriz.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, -1, -1));
        jButton2.getAccessibleContext().setAccessibleParent(this);

        getContentPane().add(jPanelMatriz, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 450, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPaqImagenes/fwer.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));
        jLabel1.getAccessibleContext().setAccessibleParent(jPanelMatriz);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPaqImagenes/negro.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 900, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBarecorridogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBarecorridogActionPerformed
       
        Ruta ruta = new Ruta();
        
        if(opcion == 1){
            System.out.println(opcion);
            AreassinProteccion obj = new AreassinProteccion();
            ruta = obj.obtenerRutaGanado(Areas.matriz);
        }
        
        if(opcion == 2){
            System.out.println(opcion);
            AreasProtegidas obj = new AreasProtegidas();
            ruta = obj.obtenerRutaG(Areas.matriz);
        }
        
        try {
            int camino[] = ruta.convertirCamino();
            dibujarMatriz(Areas.matriz, camino);
        }
        catch(IOException e) {
            System.out.print(e.getMessage());
        }
        
        jLcosto.setText("La ruta que recorrio el ganado es: " + String.valueOf(ruta.costo)+"Km");
    }//GEN-LAST:event_jBarecorridogActionPerformed
 
    private void jBregresarMouseEntered(java.awt.event.MouseEvent evt) {                                                    
        jBregresar.setBackground(Color.red);
    }   
    private void jBregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregresarActionPerformed
        GuiLeastCostPath gleast = new GuiLeastCostPath();
        gleast.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBregresarActionPerformed

     private void jBregresarMouseExited(java.awt.event.MouseEvent evt) {                                                   
        jBregresar.setBackground(new Color(51,204,0));
    }   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMatriz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBarecorridog;
    private javax.swing.JButton jBregresar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLcosto;
    public javax.swing.JPanel jPanelMatriz;
    // End of variables declaration//GEN-END:variables
}
